modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="test_mod"
version="1.0.0"
displayName="Test Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="SpaceDude609 with MCreator"
description='''
Adds stuff. Mostly Kirby related
'''

[[dependencies.test_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




